/**
 * Real-embedding quality tests for the embedding sorter.
 *
 * Uses pre-computed nomic-embed-text vectors from embedding-vectors.json
 * (generated by `pnpm --filter @amarnai/ai seed:embeddings`).
 *
 * Unlike embedding-sorter.test.ts — which uses one-hot mock vectors to test
 * algorithm geometry in isolation — these tests validate real-world
 * classification accuracy on the labeled email fixtures from sorting-fixtures.ts.
 *
 * The LLM is intentionally disabled (always returns needsHumanReview) so that
 * results reflect the embedding phase alone. Easy fixtures must route correctly;
 * medium fixtures may either route correctly or fall back to human review.
 */
import { describe, it, expect } from "vitest";
import { sortThreadByEmbedding } from "../embedding/sorter.js";
import { makeRealEmbeddingProvider } from "./fixtures/real-embedding-table.js";
import { ALL_NODES, ALL_EDGES, TEST_EMAILS } from "./fixtures/sorting-fixtures.js";
import type { AIProvider } from "../types.js";

// ─── LLM stub ─────────────────────────────────────────────────────────────────
//
// All LLM calls return needsHumanReview so results are driven by embeddings only.

const STUB_LLM: AIProvider = {
  providerName: "stub",
  modelName: "stub-llm",
  async chat() {
    return JSON.stringify({
      selectedNodeId: null,
      confidence: 0,
      explanation: "LLM disabled in real-embedding fixture tests",
      needsHumanReview: true,
    });
  },
};

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("embedding sorter — real embeddings (nomic-embed-text)", () => {
  const embeddingProvider = makeRealEmbeddingProvider();

  for (const email of TEST_EMAILS) {
    const label = `[${email.difficulty}] ${email.id} → ${email.expectedFinalNodeId}`;

    it(label, async () => {
      const result = await sortThreadByEmbedding(
        embeddingProvider,
        STUB_LLM,
        ALL_NODES,
        ALL_EDGES,
        email.messages
      );

      if (email.allowNeedsHumanReview) {
        // Correct routing OR human review are both acceptable outcomes.
        const routedCorrectly = result.finalNodeId === email.expectedFinalNodeId;
        const deferredToHuman = result.needsHumanReview;
        expect(
          routedCorrectly || deferredToHuman,
          `Expected "${email.expectedFinalNodeId}" or needsHumanReview=true.\n` +
          `  Got: finalNodeId="${result.finalNodeId}" needsHumanReview=${result.needsHumanReview}\n` +
          `  Explanation: ${result.explanation}`
        ).toBe(true);
      } else {
        // Easy cases must route correctly — no human review allowed.
        expect(
          result.finalNodeId,
          `Explanation: ${result.explanation}`
        ).toBe(email.expectedFinalNodeId);
        expect(result.needsHumanReview).toBe(false);
      }
    });
  }
});
