/**
 * Loader for pre-computed real embedding fixtures.
 *
 * embedding-vectors.json is generated by:
 *   pnpm --filter @amarnai/ai seed:embeddings
 *
 * The returned provider behaves exactly like a real EmbeddingProvider but
 * serves cached vectors instead of making network calls, keeping tests fast
 * and deterministic.
 */
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { EmbeddingProvider } from "../../embedding/types.js";

type EmbeddingFixture = {
  model: string;
  generatedAt: string;
  entries: Array<{ key: string; text: string; vector: number[] }>;
};

function loadFixture(): EmbeddingFixture {
  const path = join(dirname(fileURLToPath(import.meta.url)), "embedding-vectors.json");
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as EmbeddingFixture;
  } catch {
    throw new Error(
      "embedding-vectors.json not found. Run: pnpm --filter @amarnai/ai seed:embeddings"
    );
  }
}

/** Map of embedding text → pre-computed vector. */
export function loadRealEmbeddingTable(): ReadonlyMap<string, number[]> {
  const fixture = loadFixture();
  const map = new Map<string, number[]>();
  for (const entry of fixture.entries) {
    map.set(entry.text, entry.vector);
  }
  return map;
}

/**
 * EmbeddingProvider backed by the fixture file.
 * Throws with a clear message if a requested text is not in the fixture —
 * run the seed script to regenerate.
 */
export function makeRealEmbeddingProvider(): EmbeddingProvider {
  const fixture = loadFixture();
  const table = loadRealEmbeddingTable();

  return {
    providerName: "fixture",
    modelName: fixture.model,
    async embed(texts: string[]): Promise<number[][]> {
      return texts.map((t) => {
        const v = table.get(t);
        if (!v) {
          throw new Error(
            `No fixture vector for text (run seed:embeddings to regenerate):\n  ${t.slice(0, 120)}…`
          );
        }
        return v;
      });
    },
  };
}
