/**
 * Loader for pre-computed real embedding fixtures.
 *
 * Fixtures are stored one file per embedding model, named by model id:
 *   embedding-vectors.<model>.json   (e.g. embedding-vectors.qwen3-embedding.json,
 *                                      embedding-vectors.gemini-embedding-001.json)
 *
 * Each is generated by:
 *   pnpm --filter @aziru/ai seed:embeddings              (default: qwen3 via Ollama)
 *   EMBEDDING_PROVIDER=frontier FRONTIER_EMBEDDING_PROVIDER=gemini … seed:embeddings
 *
 * The returned provider behaves exactly like a real EmbeddingProvider but
 * serves cached vectors instead of making network calls, keeping tests fast
 * and deterministic. Selecting a model lets the grid search be judged on the
 * model actually deployed (Gemini) while keeping qwen3 as an offline/keyless
 * default for CI.
 */
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { EmbeddingProvider } from "../../embedding/types.js";

/**
 * Model whose fixture is loaded when no model is requested. qwen3 is the
 * offline/keyless default (Ollama), so existing tests run without API keys.
 */
export const DEFAULT_FIXTURE_MODEL = "qwen3-embedding";

type EmbeddingFixture = {
  model: string;
  generatedAt: string;
  entries: Array<{ key: string; text: string; vector: number[] }>;
};

/**
 * Filename for a model's fixture. Model ids may contain characters that are
 * awkward in filenames (e.g. the "@768" dimension suffix from
 * composeEmbeddingModelId), so non-filename-safe characters are replaced with
 * "_". Used by both the seed script (write) and the loader (read) so the two
 * always agree.
 */
export function fixtureFileForModel(model: string): string {
  const safe = model.replace(/[^a-zA-Z0-9._-]/g, "_");
  return `embedding-vectors.${safe}.json`;
}

function fixturePath(model: string): string {
  return join(dirname(fileURLToPath(import.meta.url)), fixtureFileForModel(model));
}

function loadFixture(model: string): EmbeddingFixture {
  const path = fixturePath(model);
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as EmbeddingFixture;
  } catch {
    throw new Error(
      `${fixtureFileForModel(model)} not found. Generate it with:\n` +
        `  pnpm --filter @aziru/ai seed:embeddings` +
        (model === DEFAULT_FIXTURE_MODEL
          ? ""
          : `  (with EMBEDDING_PROVIDER/FRONTIER_EMBEDDING_* set to produce "${model}")`)
    );
  }
}

/** Map of embedding text → pre-computed vector for the given model. */
export function loadRealEmbeddingTable(
  model: string = DEFAULT_FIXTURE_MODEL
): ReadonlyMap<string, number[]> {
  const fixture = loadFixture(model);
  const map = new Map<string, number[]>();
  for (const entry of fixture.entries) {
    map.set(entry.text, entry.vector);
  }
  return map;
}

/**
 * EmbeddingProvider backed by a model's fixture file.
 * Throws with a clear message if a requested text is not in the fixture —
 * run the seed script to regenerate.
 */
export function makeRealEmbeddingProvider(
  model: string = DEFAULT_FIXTURE_MODEL
): EmbeddingProvider {
  const fixture = loadFixture(model);
  const table = new Map<string, number[]>();
  for (const entry of fixture.entries) table.set(entry.text, entry.vector);

  return {
    providerName: "fixture",
    modelName: fixture.model,
    async embed(texts: string[]): Promise<number[][]> {
      return texts.map((t) => {
        const v = table.get(t);
        if (!v) {
          throw new Error(
            `No fixture vector for text in "${fixture.model}" (run seed:embeddings to regenerate):\n  ${t.slice(0, 120)}…`
          );
        }
        return v;
      });
    },
  };
}
