import {
  DEFAULT_CATCH_ALL_REF,
  DEFAULT_CATCH_ALL_NAME,
  DEFAULT_CATCH_ALL_DESCRIPTION,
  DEFAULT_CATCH_ALL_POSITION,
  type TaxonomyTransferFile,
} from "@aziru/shared";

export type TaxonomyTemplate = {
  id: string;
  name: string;
  description: string;
  file: TaxonomyTransferFile;
};

const DATE = "2026-01-01T00:00:00.000Z";

// Layout: root at x=0, L1 at x=300, L2 at x=600.
// Each node's y is the midpoint of its subtree's leaf span.
// Leaves spaced 140px apart, tree centered at y=0.
//
// Vocabulary invariant: folder names and descriptions are token-disjoint across
// templates (the deterministic matcher scores unigram overlap between a template
// and the inbox profile). Each distinctive noun has a single owning template so
// a given inbox matches one template cleanly. A pairwise-overlap test in
// matchTemplateToProfile.test.ts enforces this; edit copy with that in mind.

const BASE_TEMPLATES: TaxonomyTemplate[] = [
  {
    id: "freelancer",
    name: "Freelancer",
    description:
      "For independent consultants and freelancers managing clients, projects, and finances.",
    // Leaves (top→bottom): Projects, Contracts, Invoices, Expenses, Admin, Leads, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "clients",
          name: "Clients",
          description:
            "Active project communication, deliverables, feedback, and approvals from clients.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "projects",
          name: "Projects",
          description:
            "Task coordination, milestones, and scope discussions for ongoing client work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "contracts",
          name: "Contracts",
          description:
            "Client contracts, statements of work, NDAs, and signed amendments.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "finance",
          name: "Finance",
          description:
            "Billing, payments, invoices, and financial records for freelance work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -70,
        },
        {
          ref: "invoices",
          name: "Invoices",
          description:
            "Invoices issued to clients and follow-ups on unpaid amounts.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -140,
        },
        {
          ref: "expenses",
          name: "Expenses",
          description:
            "Business reimbursements and records of work-related purchases and equipment.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: 0,
        },
        {
          ref: "admin",
          name: "Admin",
          description:
            "Business registration, liability coverage, and internal administration notices.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "leads",
          name: "Leads",
          description:
            "New business inquiries, project proposals, and pricing discussions from prospective clients.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to freelance work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "clients" },
        { sourceRef: "clients", targetRef: "projects" },
        { sourceRef: "clients", targetRef: "contracts" },
        { sourceRef: "root", targetRef: "finance" },
        { sourceRef: "finance", targetRef: "invoices" },
        { sourceRef: "finance", targetRef: "expenses" },
        { sourceRef: "root", targetRef: "admin" },
        { sourceRef: "root", targetRef: "leads" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "employee",
    name: "Working Professional",
    description:
      "For employees managing work, team communication, and personal email in one inbox.",
    // Leaves (top→bottom): Team, Management, Partners, Recruiting, Finance, Admin, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "work",
          name: "Work",
          description:
            "Professional emails related to job duties and workplace activities.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -210,
        },
        {
          ref: "team",
          name: "Team",
          description:
            "Internal communication with colleagues, team updates, and workplace collaboration.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "management",
          name: "Management",
          description:
            "Manager emails: one-on-ones, performance evaluations, and career feedback.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "partners",
          name: "Partners",
          description:
            "External agencies, outside firms, and business partners engaged professionally.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -140,
        },
        {
          ref: "recruiting",
          name: "Recruiting",
          description:
            "Recruiter outreach, role applications, interview scheduling, and staffing packages.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: 0,
        },
        {
          ref: "finance",
          name: "Finance",
          description:
            "Payslips, salary statements, and employee benefits and pension emails.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "admin",
          name: "Admin",
          description:
            "IT support, HR notices, policy documents, and internal administrative emails.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "work" },
        { sourceRef: "work", targetRef: "team" },
        { sourceRef: "work", targetRef: "management" },
        { sourceRef: "work", targetRef: "partners" },
        { sourceRef: "work", targetRef: "recruiting" },
        { sourceRef: "root", targetRef: "finance" },
        { sourceRef: "root", targetRef: "admin" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "founder",
    name: "Startup Founder",
    description:
      "For founders juggling investors, customers, hiring, legal, and press in one view.",
    // Leaves (top→bottom): Investors, Customers, Hiring, Operations, Legal, Press, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "investors",
          name: "Investors",
          description:
            "Updates, term sheets, due diligence requests, cap table, and investor relations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -420,
        },
        {
          ref: "customers",
          name: "Customers",
          description:
            "Support, onboarding, retention, churn, and customer success conversations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -280,
        },
        {
          ref: "team",
          name: "Team",
          description:
            "Internal communications, HR, staff coordination, and team operational emails.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -70,
        },
        {
          ref: "hiring",
          name: "Hiring",
          description:
            "Candidate pipelines, applicant screening, and headcount planning.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -140,
        },
        {
          ref: "operations",
          name: "Operations",
          description:
            "Vendor agreements, office logistics, and day-to-day operational coordination.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: 0,
        },
        {
          ref: "legal",
          name: "Legal",
          description:
            "Agreements, banking, accounting, incorporation, and corporate legal correspondence.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "press",
          name: "Press",
          description:
            "Media inquiries, journalist requests, and press coverage bookings.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to the startup.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "investors" },
        { sourceRef: "root", targetRef: "customers" },
        { sourceRef: "root", targetRef: "team" },
        { sourceRef: "team", targetRef: "hiring" },
        { sourceRef: "team", targetRef: "operations" },
        { sourceRef: "root", targetRef: "legal" },
        { sourceRef: "root", targetRef: "press" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "student",
    name: "Student",
    description:
      "For students balancing university, internship applications, and everyday life.",
    // Leaves (top→bottom): Courses, Campus Admin, Jobs, Finance, Social, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "university",
          name: "University",
          description:
            "Official university emails: registrar, student services, and housing.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -280,
        },
        {
          ref: "courses",
          name: "Courses",
          description:
            "Professors, assignments, study groups, course announcements, and academic deadlines.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -350,
        },
        {
          ref: "campus_admin",
          name: "Campus Admin",
          description:
            "Enrollment, tuition fees, dorm assignments, and official campus administration.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -210,
        },
        {
          ref: "jobs",
          name: "Jobs",
          description:
            "Internship postings, campus career fairs, and graduate scheme openings.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -70,
        },
        {
          ref: "finance",
          name: "Finance",
          description:
            "Student loans, rent payments, and financial aid notifications.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 70,
        },
        {
          ref: "social",
          name: "Social",
          description:
            "Friends, campus clubs, social invitations, and extracurricular activities.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 210,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and non-academic emails for everyday life.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 350,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "university" },
        { sourceRef: "university", targetRef: "courses" },
        { sourceRef: "university", targetRef: "campus_admin" },
        { sourceRef: "root", targetRef: "jobs" },
        { sourceRef: "root", targetRef: "finance" },
        { sourceRef: "root", targetRef: "social" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "personal",
    name: "Personal / Family",
    description:
      "For individuals managing finances, health, home, family, and personal subscriptions.",
    // Leaves (top→bottom): Taxes, Bills & Receipts, Health, Home, Family, Travel, Subscriptions
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "finance",
          name: "Finance",
          description:
            "Bank statements, investments, insurance policies, and personal financial records.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "taxes",
          name: "Taxes",
          description:
            "Tax returns, government notices, fines, and annual contributions to state authorities.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "invoices",
          name: "Bills & Receipts",
          description:
            "Household bills, payment confirmations, receipts, and records of everyday expenses.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "health",
          name: "Health",
          description:
            "Doctors, pharmacies, medical appointments, prescriptions, and test results.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "home",
          name: "Home",
          description:
            "Utilities, household maintenance, and home upkeep appointments.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "family",
          name: "Family",
          description:
            "Emails from relatives, children's activities, family events, and household coordination.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "travel",
          name: "Travel",
          description:
            "Flight and hotel bookings, travel itineraries, visas, and trip confirmations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "subscriptions",
          name: "Subscriptions",
          description:
            "Streaming services, app subscriptions, memberships, and recurring billing notices.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "finance" },
        { sourceRef: "finance", targetRef: "taxes" },
        { sourceRef: "finance", targetRef: "invoices" },
        { sourceRef: "root", targetRef: "health" },
        { sourceRef: "root", targetRef: "home" },
        { sourceRef: "root", targetRef: "family" },
        { sourceRef: "root", targetRef: "travel" },
        { sourceRef: "root", targetRef: "subscriptions" },
      ],
    },
  },
  {
    id: "software-developer",
    name: "Software Developer",
    description:
      "For engineers and open-source maintainers tracking code, deployments, and releases.",
    // Leaves (top→bottom): Pull Requests, Bug Reports, Deployments, Incidents, Releases, Communities, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "code",
          name: "Code",
          description:
            "Source-control activity, branch changes, and merge approvals across repositories.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "pull_requests",
          name: "Pull Requests",
          description:
            "Pull request notifications, merge-approval mentions, and comment threads on repositories.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "bugs",
          name: "Bug Reports",
          description:
            "Bug reports, stack traces, and regression tickets filed against the codebase.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "infrastructure",
          name: "Infrastructure",
          description:
            "Cloud hosting, servers, and platform monitoring for running services.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -70,
        },
        {
          ref: "deployments",
          name: "Deployments",
          description:
            "Continuous-integration runs, build pipelines, and deployment status notifications.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -140,
        },
        {
          ref: "incidents",
          name: "Incidents",
          description:
            "On-call alerts, outage reports, and production incident escalations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: 0,
        },
        {
          ref: "releases",
          name: "Releases",
          description:
            "Version releases, changelogs, dependency upgrades, and package registry alerts.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "communities",
          name: "Communities",
          description:
            "Open-source maintainers, contributor discussions, and developer forum threads.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to software work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "code" },
        { sourceRef: "code", targetRef: "pull_requests" },
        { sourceRef: "code", targetRef: "bugs" },
        { sourceRef: "root", targetRef: "infrastructure" },
        { sourceRef: "infrastructure", targetRef: "deployments" },
        { sourceRef: "infrastructure", targetRef: "incidents" },
        { sourceRef: "root", targetRef: "releases" },
        { sourceRef: "root", targetRef: "communities" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "ecommerce-seller",
    name: "E-commerce Seller",
    description:
      "For online sellers tracking orders, shipping, suppliers, and marketplace payouts.",
    // Leaves (top→bottom): Shipping, Returns, Suppliers, Marketplaces, Buyer Questions, Payouts & Fees, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "orders",
          name: "Orders",
          description:
            "Purchase confirmations, order status changes, and fulfillment updates from your store.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "shipping",
          name: "Shipping",
          description:
            "Carrier tracking numbers, delivery exceptions, and courier dispatch notices.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "returns",
          name: "Returns",
          description:
            "Return requests, refund approvals, and exchange labels from shoppers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "suppliers",
          name: "Suppliers",
          description:
            "Wholesale suppliers, restock orders, and inventory availability from manufacturers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "marketplaces",
          name: "Marketplaces",
          description:
            "Storefront notices from Amazon, Etsy, eBay, and marketplace store accounts.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "buyers",
          name: "Customer Questions",
          description:
            "Pre-sale questions and messages from prospective shoppers about products.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "payouts",
          name: "Payouts & Fees",
          description:
            "Store payouts, chargebacks, selling fees, and settlement statements.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to the shop.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "orders" },
        { sourceRef: "orders", targetRef: "shipping" },
        { sourceRef: "orders", targetRef: "returns" },
        { sourceRef: "root", targetRef: "suppliers" },
        { sourceRef: "root", targetRef: "marketplaces" },
        { sourceRef: "root", targetRef: "buyers" },
        { sourceRef: "root", targetRef: "payouts" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "content-creator",
    name: "Content Creator",
    description:
      "For creators handling brand deals, platforms, audience, and monetization.",
    // Leaves (top→bottom): Sponsorships, Affiliate Programs, Platforms, Collaborations, Audience, Monetization, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "brand_deals",
          name: "Brand Deals",
          description:
            "Sponsored placements, brand partnerships, and promotional collaborations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "sponsorships",
          name: "Sponsorships",
          description:
            "Sponsorship rates, content briefs, and paid placement deals.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "affiliates",
          name: "Affiliates",
          description:
            "Affiliate links, referral commissions, and creator reward tiers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "platforms",
          name: "Platforms",
          description:
            "Channel notifications, upload analytics, and policy updates from social platforms.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "collaborations",
          name: "Collaborations",
          description:
            "Collab invitations, guest appearances, and cross-promotion with other creators.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "audience",
          name: "Audience",
          description:
            "Fan messages, viewer comments, and follower engagement notifications.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "monetization",
          name: "Monetization",
          description:
            "Ad revenue, fan tips, and creator earnings statements.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to content work.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "brand_deals" },
        { sourceRef: "brand_deals", targetRef: "sponsorships" },
        { sourceRef: "brand_deals", targetRef: "affiliates" },
        { sourceRef: "root", targetRef: "platforms" },
        { sourceRef: "root", targetRef: "collaborations" },
        { sourceRef: "root", targetRef: "audience" },
        { sourceRef: "root", targetRef: "monetization" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "teacher",
    name: "Teacher",
    description:
      "For K-12 educators managing classroom, parents, and school administration.",
    // Leaves (top→bottom): Homework & Grading, Lesson Planning, Parents & Guardians, School Administration, Events & Field Trips, Professional Development, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "classroom",
          name: "Classroom",
          description:
            "Pupil questions, homework hand-ins, and daily instruction in the classroom.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "grading",
          name: "Homework & Grading",
          description:
            "Graded homework, rubric feedback, and marks recorded for each pupil.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "lesson_planning",
          name: "Lesson Planning",
          description:
            "Curriculum resources, lesson materials, and syllabus planning for upcoming units.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "parents",
          name: "Parents & Guardians",
          description:
            "Messages from parents and guardians about attendance, behavior, and progress.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "school_admin",
          name: "School Administration",
          description:
            "Principal notices, staff meetings, and district administration bulletins.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "events",
          name: "Events & Field Trips",
          description:
            "Field trips, parent evenings, assemblies, and school event scheduling.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "development",
          name: "Professional Development",
          description:
            "Teacher training workshops, certification renewals, and education webinars.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to teaching.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "classroom" },
        { sourceRef: "classroom", targetRef: "grading" },
        { sourceRef: "classroom", targetRef: "lesson_planning" },
        { sourceRef: "root", targetRef: "parents" },
        { sourceRef: "root", targetRef: "school_admin" },
        { sourceRef: "root", targetRef: "events" },
        { sourceRef: "root", targetRef: "development" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "academic-researcher",
    name: "Academic Researcher",
    description:
      "For researchers managing publications, conferences, funding, and lab work.",
    // Leaves (top→bottom): Manuscripts & Peer Review, Journals, Conferences, Funding & Fellowships, Lab & Collaborators, Supervision, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "publications",
          name: "Publications",
          description:
            "Manuscript drafts, co-author coordination, and submission status for papers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "peer_review",
          name: "Manuscripts & Peer Review",
          description:
            "Referee invitations, reviewer reports, and revision requests from journal editors.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "journals",
          name: "Journals",
          description:
            "Journal calls for papers, special issue invitations, and citation metrics.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "conferences",
          name: "Conferences",
          description:
            "Conference submissions, abstract acceptances, and keynote session invitations.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "funding",
          name: "Funding & Fellowships",
          description:
            "Fellowship awards, funding-body deadlines, and research budget correspondence.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "lab",
          name: "Lab & Collaborators",
          description:
            "Lab group updates, collaborator threads, and experiment coordination.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "supervision",
          name: "Supervision",
          description:
            "Doctoral advising, thesis feedback, and mentoring for doctoral researchers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to research.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "publications" },
        { sourceRef: "publications", targetRef: "peer_review" },
        { sourceRef: "publications", targetRef: "journals" },
        { sourceRef: "root", targetRef: "conferences" },
        { sourceRef: "root", targetRef: "funding" },
        { sourceRef: "root", targetRef: "lab" },
        { sourceRef: "root", targetRef: "supervision" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "real-estate-agent",
    name: "Real Estate Agent",
    description:
      "For agents managing listings, showings, transactions, and closings.",
    // Leaves (top→bottom): Listings, Buyers & Showings, Sellers, Escrow & Closing, Inspections & Appraisals, Lenders & Mortgage, New Inquiries, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "listings",
          name: "Listings",
          description:
            "Property listings, MLS updates, staging, and photography scheduling.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -490,
        },
        {
          ref: "buyers",
          name: "Buyers & Showings",
          description:
            "Showing requests, buyer tours, open-house sign-ups, and written offers.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "sellers",
          name: "Sellers",
          description:
            "Seller consultations, listing paperwork, price reductions, and market appraisals.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -210,
        },
        {
          ref: "transactions",
          name: "Transactions",
          description:
            "Deal progress, transaction stages, and closing coordination across active sales.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "escrow",
          name: "Escrow & Closing",
          description:
            "Escrow instructions, title documents, closing disclosures, and signing appointments.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -70,
        },
        {
          ref: "inspections",
          name: "Inspections & Appraisals",
          description:
            "Home inspections, appraisal reports, repair negotiations, and contingency deadlines.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: 70,
        },
        {
          ref: "lenders",
          name: "Lenders & Mortgage",
          description:
            "Mortgage brokers, financing pre-approvals, rate quotes, and underwriting updates.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 210,
        },
        {
          ref: "inquiries",
          name: "New Inquiries",
          description:
            "First-contact buyer and seller enquiries and new agent introductions.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 350,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to real estate.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 490,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "listings" },
        { sourceRef: "root", targetRef: "buyers" },
        { sourceRef: "root", targetRef: "sellers" },
        { sourceRef: "root", targetRef: "transactions" },
        { sourceRef: "transactions", targetRef: "escrow" },
        { sourceRef: "transactions", targetRef: "inspections" },
        { sourceRef: "root", targetRef: "lenders" },
        { sourceRef: "root", targetRef: "inquiries" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
  {
    id: "nonprofit-leader",
    name: "Nonprofit Leader",
    description:
      "For nonprofit directors managing fundraising, volunteers, programs, and board.",
    // Leaves (top→bottom): Donors, Grants & Foundations, Volunteers, Programs, Board & Governance, Events & Campaigns, Personal
    file: {
      amarnaiTaxonomyVersion: 1,
      exportedAt: DATE,
      nodes: [
        {
          ref: "root",
          name: "Inbox",
          description: null,
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: true,
          positionX: 0,
          positionY: 0,
        },
        {
          ref: "fundraising",
          name: "Fundraising",
          description:
            "Donation drives, giving campaigns, and fundraising appeal responses.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -350,
        },
        {
          ref: "donors",
          name: "Donors",
          description:
            "Major donor relationships, pledge confirmations, and gift acknowledgements.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -420,
        },
        {
          ref: "grants",
          name: "Grants & Foundations",
          description:
            "Grant requests, foundation deadlines, and funder reporting requirements.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 600,
          positionY: -280,
        },
        {
          ref: "volunteers",
          name: "Volunteers",
          description:
            "Volunteer sign-ups, shift scheduling, and coordinator communications.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: -140,
        },
        {
          ref: "programs",
          name: "Programs",
          description:
            "Program operations, beneficiary services, and impact reporting updates.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 0,
        },
        {
          ref: "board",
          name: "Board & Governance",
          description:
            "Board meetings, governance policies, bylaws, and trustee correspondence.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 140,
        },
        {
          ref: "events",
          name: "Events & Campaigns",
          description:
            "Gala planning, charity auctions, and awareness campaign logistics.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 280,
        },
        {
          ref: "personal",
          name: "Personal",
          description:
            "Personal correspondence and emails unrelated to the organization.",
          instructions: null,
          draftPrompt: null,
          examples: [],
          isRoot: false,
          positionX: 300,
          positionY: 420,
        },
      ],
      edges: [
        { sourceRef: "root", targetRef: "fundraising" },
        { sourceRef: "fundraising", targetRef: "donors" },
        { sourceRef: "fundraising", targetRef: "grants" },
        { sourceRef: "root", targetRef: "volunteers" },
        { sourceRef: "root", targetRef: "programs" },
        { sourceRef: "root", targetRef: "board" },
        { sourceRef: "root", targetRef: "events" },
        { sourceRef: "root", targetRef: "personal" },
      ],
    },
  },
];

// Every template gets a non-routable catch-all folder. Automated/bulk mail
// (notifications, newsletters, service updates) is auto-filed here without an
// LLM call; it is excluded from normal embedding/LLM routing (isCatchAll).
const CATCH_ALL_NODE: TaxonomyTransferFile["nodes"][number] = {
  ref: DEFAULT_CATCH_ALL_REF,
  name: DEFAULT_CATCH_ALL_NAME,
  description: DEFAULT_CATCH_ALL_DESCRIPTION,
  instructions: null,
  draftPrompt: null,
  examples: [],
  isRoot: false,
  isCatchAll: true,
  positionX: DEFAULT_CATCH_ALL_POSITION.x,
  positionY: DEFAULT_CATCH_ALL_POSITION.y,
};

const CATCH_ALL_EDGE: TaxonomyTransferFile["edges"][number] = {
  sourceRef: "root",
  targetRef: DEFAULT_CATCH_ALL_REF,
};

export const TAXONOMY_TEMPLATES: TaxonomyTemplate[] = BASE_TEMPLATES.map((t) => ({
  ...t,
  file: {
    ...t.file,
    nodes: [...t.file.nodes, { ...CATCH_ALL_NODE }],
    edges: [...t.file.edges, { ...CATCH_ALL_EDGE }],
  },
}));
