export type { ApiTransport, TransportInit } from "./transport.js";
export { makeApiClient } from "./client.js";
export type { ApiClient } from "./client.js";
export type {
  Workspace,
  TaxonomyNode,
  CreateTaxonomyNodeInput,
  UpdateTaxonomyNodeInput,
  TaxonomyEdge,
  CreateTaxonomyEdgeInput,
  UpdateTaxonomyEdgeInput,
  UpdateGmailSyncSettingsInput,
  GmailConnection,
  ConnectGmailInput,
  DisconnectResult,
  SyncStatus,
  BackfillStatus,
  GmailSyncSettings,
  FolderCountsResult,
  FilterCounts,
  EmailTag,
  ClassificationSummary,
  Classification,
  EmailThreadSummary,
  EmailThreadListResult,
  EmailThreadDetail,
  TriageStatus,
  DoneMark,
  Draft,
  GenerateDraftResult,
  MockInboxEventInput,
  MockInboxResult,
  CandidateNodeInput,
  CandidateNode,
  CandidateNodeResult,
  LLMNodeSelectionResult,
  GmailRecentThreadsResult,
  GmailSortPathStep,
  GmailSortResult,
  ClassifyResult,
  QueuedResult,
  OkResult,
  QuotaInfo,
  CurrentUser,
  DevicePlatform,
  RegisterPushDeviceInput,
  RegisterPushDeviceResult,
} from "./types.js";
